# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eddf2824943a77c27bed7fd954303491b2b9c7ce5cb33a187b85b1dd9a909176240648bcfcf57454f65d492e10dee5a50396c38d77272f219be605733ca4b9b6

test:
  secret_key_base: ec0afda9b2463738a617c9c53e685a06fc507e0b2c6f142d4e1d67b8420d7913fc8b71aac6283eaffb461ce7367d74354bc9af76e44fe65aef0bd6d10c3c35e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
